### ISSUE TITLE
Historische Wetterdaten hinzufügen

### ISSUE THREAD

**Issue by felixbublitz** [tuppp/mkp_read_data#4]
Historische Wetterdaten werden zur Zeit noch nicht heruntergeladen. Außerdem gibt es Überschneidungen bei den historischen und aktuellen Wetterdaten. Dies muss berücksichtigt werden.

**Comment by mmette** [comment]
Genauer, es geht um diese beiden Links:
ftp://ftp-cdc.dwd.de/pub/CDC/observations_germany/climate/daily/kl/historical/
ftp://ftp-cdc.dwd.de/pub/CDC/observations_germany/climate/daily/kl/recent/

Beispiel (Station mit der ID=44):
Historical: von 01.03.1971 bis 31.12.2017
Recent: von 25.11.2016 bis 28.05.2018
-> Überschneidung von ca 1 Jahr
